[project]
name = "graph-vs-relational"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.2",
    "neo4j>=5.28.1",
    "pandas>=2.2.3",
    "psycopg[binary]>=3.2.7",
]
